namespace SummaRace.Tests.EditMode
{
    using System.Collections.Generic;
    using System.IO;
    using NUnit.Framework;
    using UnityEditor;
    using UnityEditor.Build;

    /// <summary>
    /// 100% offline is a GDD non-negotiable AND a term of the study's consent: no networking, no
    /// ads, no analytics, no IAP. `SummaRace ▸ Build Preflight` checks this, but a preflight is a
    /// menu item someone has to remember on the one day they are busiest. This is the same rule
    /// as a test, so it fails in CI and in the Test Runner instead.
    ///
    /// It guards the SOURCE of the regression rather than its symptom. Trash Dash's shop,
    /// leaderboard and rewarded-ad code is still in the project — 49 call sites — and it is inert
    /// only because `UNITY_ADS` / `UNITY_ANALYTICS` / `UNITY_PURCHASING` are undefined. Nobody has
    /// to edit a single one of those files to arm them: Unity defines those symbols
    /// AUTOMATICALLY when the matching package is present. So the thing to assert is the package
    /// list and the define symbols, not the call sites.
    ///
    /// This has happened twice. The "EXPERIMENT 2: full Endless Runner import" silently added
    /// com.unity.ads, com.unity.analytics and com.unity.purchasing to the manifest, and Google's
    /// VersionHandler re-created `Resources/BillingMode.json` after it was deleted once. Neither
    /// was noticed by reading the game; both were found by reading the manifest.
    /// </summary>
    public class OfflineComplianceTests
    {
        /// <summary>Substrings, not exact ids: the family matters, not the exact package name
        /// (`com.unity.purchasing` and `com.unity.purchasing.udp` are both banned).</summary>
        private static readonly string[] BannedPackages =
        {
            "com.unity.ads",
            "com.unity.analytics",
            "com.unity.purchasing",
            "com.unity.services.analytics",
            "com.unity.services.levelplay",
            "com.unity.microsoft.gdk",
        };

        /// <summary>Defined by Unity itself when the matching package is installed. Their presence
        /// is what would compile Trash Dash's dormant ad/analytics code back in.</summary>
        private static readonly string[] BannedDefines =
        {
            "UNITY_ADS",
            "UNITY_ANALYTICS",
            "UNITY_PURCHASING",
        };

        [Test]
        public void ManifestDeclaresNoAdsAnalyticsOrPurchasingPackage()
        {
            var manifest = Path.Combine("Packages", "manifest.json");
            Assert.IsTrue(File.Exists(manifest), "Packages/manifest.json is missing.");

            var text = File.ReadAllText(manifest);
            var found = new List<string>();
            foreach (var banned in BannedPackages)
                if (text.Contains(banned)) found.Add(banned);

            StoryContentTests.AssertNoFailures(found,
                "banned packages in Packages/manifest.json. Installing one of these does not just " +
                "add a dependency — it makes Unity define UNITY_ADS / UNITY_ANALYTICS / " +
                "UNITY_PURCHASING, which compiles Trash Dash's dormant shop, leaderboard and " +
                "rewarded-ad code back into the player. The app is required to be 100% offline");
        }

        [Test]
        public void AndroidDefinesNoAdsAnalyticsOrPurchasingSymbol()
        {
            var defines = PlayerSettings.GetScriptingDefineSymbols(
                NamedBuildTarget.Android) ?? string.Empty;

            var found = new List<string>();
            foreach (var symbol in defines.Split(';'))
            {
                var trimmed = symbol.Trim();
                foreach (var banned in BannedDefines)
                    if (string.Equals(trimmed, banned, System.StringComparison.Ordinal))
                        found.Add(banned);
            }

            StoryContentTests.AssertNoFailures(found,
                "banned scripting define symbols on Android. Each one arms a block of dormant " +
                "third-party ad/analytics code that is currently compiled out. Current Android " +
                "defines: " + (string.IsNullOrEmpty(defines) ? "(none)" : defines));
        }

        [Test]
        public void GooglesBillingModeResourceHasNotComeBack()
        {
            // Deleting this once was not enough: Google's VersionHandler re-created it after a
            // domain reload, so it had to be deleted a second time with the Editor closed. Its
            // reappearance means a purchasing dependency has been reintroduced somewhere.
            var billing = Path.Combine("Assets", "Resources", "BillingMode.json");
            Assert.IsFalse(File.Exists(billing),
                "Assets/Resources/BillingMode.json exists again. It is generated by Google's " +
                "play-billing resolver, so something has reintroduced a purchasing dependency. " +
                "Delete it with the Editor CLOSED — it self-resurrects across a domain reload.");
        }

        [Test]
        public void EveryUnityServiceIsDisabled()
        {
            var path = Path.Combine("ProjectSettings", "UnityConnectSettings.asset");
            Assert.IsTrue(File.Exists(path), "ProjectSettings/UnityConnectSettings.asset is missing.");

            var failures = new List<string>();
            foreach (var line in File.ReadAllLines(path))
            {
                var trimmed = line.Trim();
                // Every m_Enabled in this asset belongs to a service block (ads, analytics,
                // purchasing, crash reporting, performance reporting). None may be on.
                if (trimmed.StartsWith("m_Enabled:", System.StringComparison.Ordinal) &&
                    !trimmed.EndsWith("0", System.StringComparison.Ordinal))
                    failures.Add(trimmed);
            }

            StoryContentTests.AssertNoFailures(failures,
                "enabled Unity services in UnityConnectSettings.asset. A service enabled here " +
                "phones home from the built app regardless of what the game's own code does");
        }
    }
}
